ChatNetChallenge/Chat.Presentation.Client/Controllers/MessagesController.cs
using System.Threading.Tasks;
using Chat.Presentation.Client.Hubs;
using Chat.Presentation.Client.Interfaces;
using Chat.Presentation.Client.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Newtonsoft.Json;

namespace Chat.Presentation.Client.Controllers
{
    [Authorize]
    public class MessagesController : Controller
    {
        private readonly IMessageServices _messageServices;
        private readonly IHubContext<ChatHub> _hubContext;

        public MessagesController(IMessageServices messageServices, IHubContext<ChatHub> hubContext)
        {
            _messageServices = messageServices;
            _hubContext = hubContext;
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetAllChatMessages()
        {
            var messages = await _messageServices.GetAllMessages();         
            string JsonContext = JsonConvert.SerializeObject(messages, Formatting.Indented, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });

            return Json(JsonContext);
        }

        [HttpPost]
        public async Task<IActionResult> SendMessage(MessageInputDataModel model)
        {
            if (ModelState.IsValid)
            {
                var messageSend = await _messageServices.SendMessage(model);

                if (!messageSend.Status)
                {
                    return RedirectToAction("Create");
                }
                string JsonContext = JsonConvert.SerializeObject(messageSend, Formatting.Indented, new JsonSerializerSettings()
                {
                    ReferenceLoopHandling = ReferenceLoopHandling.Ignore
                });

                await _hubContext.Clients.All.SendAsync("Message", JsonContext);
                return Ok();
            }
            return BadRequest();
        }
      
    }
}

ChatNetChallenge/Chat.Presentation.Client/Views/Messages/Create.cshtml
@{
    ViewData["Title"] = "Create";
    var emailUser = User.FindFirst(System.Security.Claims.ClaimTypes.Email).Value;
}

<link rel="stylesheet" href="~/css/ChatStyle.css" />

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Chat</h4>
        </div>
        <div class="panel-body">
            <ul class="chat" id="chatBody">
                <li class="left clearfix">
                </li>
            </ul>
        </div>
        <input id="visitChatSeletedId" hidden value="0">
        <div class="panel-footer">
            <div class="input-group">
                <input id="btn_input" type="text" class="form-control input-sm" placeholder="Write your message here..." />
                <span class="input-group-btn">
                    <button class="btn btn-warning btn-sm" id="btn_chat">
                        Send
                    </button>
                </span>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        var urlSendMessage = '@Url.Action("SendMessage", "Messages")';
        var urlGetAllChatMessages = '@Url.Action("GetAllChatMessages", "Messages")';
        var emailUserFromIdentity = '@emailUser';
    </script>
    <script src="~/js/chatBot.min.js"></script>
}