ChatNetChallenge/Chat.Presentation.Client/Controllers/LoginsController.cs
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using Chat.Presentation.Client.Core;
using Chat.Presentation.Client.Interfaces;
using Chat.Presentation.Client.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Chat.Presentation.Client.Controllers
{
    public class LoginsController : Controller
    {

        private readonly ILoginServices _loginServices;
        private readonly Hash _hash;
        public LoginsController(Hash hash, ILoginServices loginServices)
        {
            _hash = hash;
            _loginServices = loginServices;
        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Index(LoginViewModels model)
        {
            if (ModelState.IsValid)
            {
                var loginModelInputData = new LoginInputDataModel
                {
                    Email = model.Input.Email,                    
                    Password = _hash.EncryptString(model.Input.Password)
                };

                var login = await _loginServices.CheckCredencial(loginModelInputData);

                if (!login.Status)
                {
                    model.ErrorMessage = login.Error;
                    return View(model);
                }

                if (!login.APIResponse)
                {
                    model.ErrorMessage = "Incorrect credentials";
                    return View(model);
                }

                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Email, model.Input.Email)
                };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var authProperties = new AuthenticationProperties();
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);

                return RedirectToAction("Create", "Messages");
            }
            model.ErrorMessage = "Wrong Data";
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Login");
        }
    }
}

ChatNetChallenge/Chat.Presentation.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - .Net Challenge</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Messages" asp-action="Create">.Net Challenge</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div id="navbarNavDropdown" class="navbar-collapse collapse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Messages" asp-action="Create">Chat</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-lg-grow-0">
                        <li class="nav-item">
                            Hello @User.FindFirst(System.Security.Claims.ClaimTypes.Email).Value
                        </li>
                        <li class="nav-item">
                            <form asp-controller="Logins" asp-action="Logout" method="post">
                                <button type="submit" class="btn btn-link navbar-btn navbar-link">Log Out</button>
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - .Net Challenge
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/aspnet/signalr/dist/browser/signalr.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ChatNetChallenge/Chat.Presentation.Client/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>